# Generated by Django 5.1 on 2025-03-30 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Completed_orders_book',
        ),
        migrations.AddField(
            model_name='ask',
            name='a_ID',
            field=models.CharField(default=20, max_length=500000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ask',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='b_ID',
            field=models.CharField(default=30, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='IDNum',
            field=models.CharField(max_length=500000, unique=True),
        ),
        migrations.CreateModel(
            name='CompletedAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_ID', models.CharField(max_length=500000, unique=True)),
                ('askprice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('noaskedshares', models.BigIntegerField()),
                ('askedwhen', models.DateTimeField()),
                ('last_interacted_with', models.DateTimeField()),
                ('closed_with', models.CharField(blank=True, max_length=500000, null=True, unique=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asker_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.id')),
                ('team_to_ask_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedBids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_ID', models.CharField(max_length=500, unique=True)),
                ('bidprice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nobidshares', models.BigIntegerField()),
                ('bidwhen', models.DateTimeField()),
                ('last_interacted_with', models.DateTimeField()),
                ('closed_with', models.CharField(blank=True, max_length=500000, null=True, unique=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bidder_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.id')),
                ('team_to_bid_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('completed_ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.completedasks')),
                ('completed_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.completedbids')),
            ],
        ),
    ]
