# Generated by Django 5.1 on 2025-04-15 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_team_completed_orders_book_ask_a_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ID',
            new_name='UsersID',
        ),
    ]
