# Generated by Django 5.1 on 2025-04-20 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team_money_alter_induvidual_ask_closed_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='induvidual_ask',
            name='a_ID',
        ),
        migrations.RemoveField(
            model_name='induvidual_bid',
            name='b_ID',
        ),
        migrations.RemoveField(
            model_name='induvidual_completedasks',
            name='a_ID',
        ),
        migrations.RemoveField(
            model_name='induvidual_completedbids',
            name='b_ID',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Teams_Unit_Share_Price',
        ),
        migrations.AddField(
            model_name='induvidual_ask',
            name='asking_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asks_by_team', to='home.team'),
        ),
        migrations.AddField(
            model_name='induvidual_completedasks',
            name='asking_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_asks_by_team', to='home.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='Base_Valuation',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='Teams_current_valuation',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='Teams_number_of_shares_with_company',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='induvidual_ask',
            name='asker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='induvidual_ask',
            name='asker_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usersid'),
        ),
        migrations.AlterField(
            model_name='induvidual_ask',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='induvidual_ask',
            name='team_to_ask_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks_on_team', to='home.team'),
        ),
        migrations.AlterField(
            model_name='induvidual_bid',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='induvidual_completedasks',
            name='asker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='induvidual_completedasks',
            name='asker_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usersid'),
        ),
        migrations.AlterField(
            model_name='induvidual_completedasks',
            name='team_to_ask_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_asks_on_team', to='home.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Induvidual_Number_of_shares_in_market',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='team',
            name='Induvidual_Unit_Share_Price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='Money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
