# Generated by Django 5.1 on 2025-04-20 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_induvidual_ask_a_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Induvidual_Ask',
            new_name='Individual_Ask',
        ),
        migrations.RenameModel(
            old_name='Induvidual_Bid',
            new_name='Individual_Bid',
        ),
        migrations.RenameModel(
            old_name='Induvidual_CommentonTeam',
            new_name='Individual_CommentonTeam',
        ),
        migrations.RenameModel(
            old_name='Induvidual_CompletedAsks',
            new_name='Individual_CompletedAsks',
        ),
        migrations.RenameModel(
            old_name='Induvidual_CompletedBids',
            new_name='Individual_CompletedBids',
        ),
        migrations.RenameModel(
            old_name='Induvidual_CompletedTransaction',
            new_name='Individual_CompletedTransaction',
        ),
        migrations.RenameModel(
            old_name='Induvidual_LinktoTeam',
            new_name='Individual_LinktoTeam',
        ),
        migrations.RenameModel(
            old_name='Induvidual_OrderBook',
            new_name='Individual_OrderBook',
        ),
        migrations.RenameModel(
            old_name='Induvidual_OrderTransaction',
            new_name='Individual_OrderTransaction',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Induvidual_Number_of_shares_in_market',
            new_name='Individual_Number_of_shares_in_market',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Induvidual_Unit_Share_Price',
            new_name='Individual_Unit_Share_Price',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Teams_current_valuation',
        ),
        migrations.CreateModel(
            name='completed_investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofshares', models.BigIntegerField()),
                ('price_bought_at', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bought_when', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('shares_of_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_whose_shares_are_being_bought', to='home.team')),
                ('team_buying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_buying_shares', to='home.team')),
            ],
        ),
    ]
