# Generated by Django 5.1 on 2025-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_team_linktoteam_delete_completed_investments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldata',
            name='peak',
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='totalmarketvalue',
        ),
        migrations.AddField(
            model_name='generaldata',
            name='temp',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
