# Generated by Django 5.1 on 2025-07-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_loans_drawn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Teams_number_of_shares_with_company',
            new_name='Teams_Number_of_shares_with_company',
        ),
    ]
