# Generated by Django 5.1 on 2025-03-27 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Number_of_shares_in_market', models.BigIntegerField(default=0)),
                ('Market_Value', models.FloatField(default=0.0)),
                ('News_and_updates', models.TextField(blank=True, max_length=100000, null=True)),
                ('Old_order_book', models.TextField(blank=True, max_length=100000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNum', models.CharField(max_length=500, unique=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserforID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('IDNum',), ('User', 'IDNum')},
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidprice', models.FloatField()),
                ('nobidshares', models.BigIntegerField()),
                ('bidwhen', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('bidder_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.id')),
                ('team_to_bid_on', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askprice', models.FloatField()),
                ('noaskedshares', models.BigIntegerField()),
                ('askedwhen', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('asker_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.id')),
                ('team_to_ask_on', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placedwhen', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('other_deets', models.TextField(max_length=10000000)),
                ('asks', models.ManyToManyField(to='home.ask')),
                ('bids', models.ManyToManyField(to='home.bid')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='LinktoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_in_team', models.BooleanField(default=False)),
                ('alert_prices', models.CharField(blank=True, max_length=100000, null=True)),
                ('stocks', models.BigIntegerField(default=0)),
                ('curuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('curuser_ID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.id')),
                ('team_linked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
            options={
                'unique_together': {('curuser_ID', 'team_linked')},
            },
        ),
        migrations.CreateModel(
            name='CommentonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('whencommented', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('commentinguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.id')),
                ('commentedteam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team')),
            ],
            options={
                'unique_together': {('userid', 'commentedteam', 'comment')},
            },
        ),
    ]
