# Generated by Django 5.1 on 2025-04-20 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_usersid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ask',
            new_name='Induvidual_Ask',
        ),
        migrations.RenameModel(
            old_name='Bid',
            new_name='Induvidual_Bid',
        ),
        migrations.RenameModel(
            old_name='CommentonTeam',
            new_name='Induvidual_CommentonTeam',
        ),
        migrations.RenameModel(
            old_name='CompletedAsks',
            new_name='Induvidual_CompletedAsks',
        ),
        migrations.RenameModel(
            old_name='CompletedBids',
            new_name='Induvidual_CompletedBids',
        ),
        migrations.RenameModel(
            old_name='CompletedTransaction',
            new_name='Induvidual_CompletedTransaction',
        ),
        migrations.RenameModel(
            old_name='LinktoTeam',
            new_name='Induvidual_LinktoTeam',
        ),
        migrations.RenameModel(
            old_name='OrderBook',
            new_name='Induvidual_OrderBook',
        ),
        migrations.RenameModel(
            old_name='OrderTransaction',
            new_name='Induvidual_OrderTransaction',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Market_Value',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Number_of_shares_in_market',
        ),
        migrations.AddField(
            model_name='team',
            name='Induvidual_Number_of_shares_in_market',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='Induvidual_Unit_Share_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='team',
            name='Teams_Number_of_shares_in_market',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='team',
            name='Teams_Unit_Share_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
