# Generated by Django 5.1 on 2025-04-20 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_ask_induvidual_ask_rename_bid_induvidual_bid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='induvidual_ask',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='induvidual_bid',
            name='closed_with',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='induvidual_ask',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_with__isnull', False)), fields=('closed_with',), name='unique_closed_with_when_not_null_ask'),
        ),
        migrations.AddConstraint(
            model_name='induvidual_bid',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_with__isnull', False)), fields=('closed_with',), name='unique_closed_with_when_not_null_bid'),
        ),
    ]
