# Generated by Django 5.1 on 2025-04-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_induvidual_ask_individual_ask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('interest', models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ('when_taken', models.DateTimeField(auto_now_add=True)),
                ('has_been_payed', models.BooleanField(default=False)),
                ('collateral_shares_of_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collateral', to='home.team')),
                ('team_taking_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_loan', to='home.team')),
            ],
        ),
    ]
