# Generated by Django 5.1 on 2025-04-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_LinktoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofshares', models.BigIntegerField()),
                ('price_bought_at', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bought_when', models.DateTimeField(auto_now_add=True)),
                ('last_interacted_with', models.DateTimeField(auto_now=True)),
                ('timeouts', models.DateTimeField(blank=True, null=True)),
                ('alert_prices', models.CharField(blank=True, max_length=100000, null=True)),
                ('invested_in_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Investing_in_this_team', to='home.team')),
                ('team_investing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_buying_shares', to='home.team')),
            ],
            options={
                'unique_together': {('team_investing', 'invested_in_team')},
            },
        ),
        migrations.DeleteModel(
            name='completed_investments',
        ),
    ]
