# Generated by Django 5.1 on 2025-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_generaldata_peak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='drawn',
            field=models.BooleanField(default=False),
        ),
    ]
