# Generated by Django 5.1 on 2025-07-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_teams_number_of_shares_with_company_team_teams_number_of_shares_with_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_orderbook',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home.team'),
        ),
    ]
